### ISSUE TITLE
Arrange Server for Database

### ISSUE THREAD

**Issue by olmageddon** [Appsterdam/DataViz#1]
Select and prepare the hosting environment for the database.

We need to select a hosting environment for the database perhaps we can use the SoftLayer setup.

**Comment by spllr** [comment]
I think we can use the SoftLayer setup for this.

We will also check with UvA and AIM if they have a place they would like this to run.

**Comment by prwteas** [comment]
I am planning to get a dedicated server with VMware ESXi and LAMP it up. Got a contact at Leaseweb and he could help to cut down some costs...

**Comment by spllr** [comment]
We have 2 quite beefy machines which are donated by SoftLayer.

I think these will be good to use. This way access is controlled by Appsterdam.

**Comment by prwteas** [comment]
Oink,oink...that's great, we go for those then...

**Comment by spllr** [comment]
Hold on:

Single Processor Quad Core Xeon 1270 - 3.40GHz (Sandy Bridge) - 1 x 8MB cache w/HT
1 X 250GB SATA II HDD
4 GB DDR3 1333
1000 Mbps Public & Private Ports
Public Bandwidth 3000 GB Bandwidth
Operating System CentOS 6.0 (64 bit)  

Dual Processor Hex Core Xeon 5670 - 2.93GHz (Westmere) - 2 x 12MB cache w/HT
RAID 1
2 X 2.00TB SATA II
12 GB DDR3 Registered 1333
1000 Mbps Public & Private Ports
Public Bandwidth 3000 GB Bandwidth
Operating System CentOS 6 (64 bit)

**Comment by prwteas** [comment]
Mmm, delicious! Trying to avoid any future implications, I'd go for the second...if it is to choose...

**Comment by spllr** [comment]
Yes, that figures :-)

We are currently setting up server policies.

Ones this is done we will see which one we will use.

We will wait till @g7morris has decided on the how and the what.

Localhost will be ok till then.

**Comment by g7morris** [comment]
So what materials/requirements do they need in the second machine?

What is the domain, they'll be using? Dbase etc?

I agree it makes more sense to keep the data viz all in the family as it were.

While a control panel is good for multiple domains, an issue arises with the mixture of nginx and apache. As so far no go. Web min may not be good for mixed environments like this.

We can of course put VMware ESXi and try to split out environments. I'm game. Still should be free license.

Will just need to read up on what SOFTLAYER offers thru its panel.

Can we discuss the policies?

Don't want to be only person deciding. Not fair per se.

**Comment by prwteas** [comment]
Have no issues in console admin'ing a LAMP, don't think nginx would be an issue instead of apache either...ESXi comes with free license indeed. 

We are planning to go with RoR on development, domain name still to be selected but would be no prob if subdomain.domain.xxx is used for the early days...

Have worked with and currently pointing to mySQL but am open to discuss any other insights...

**Comment by g7morris** [comment]
Ok great. That makes it clear. Thanks!

Let me discuss a few things with Klaas and then we can all work out how to proceed. 

Exciting idea, can't wait to see the execution.

Good luck.

**Comment by prwteas** [comment]
Thank you very much monsieur!!

**Comment by spllr** [comment]
Yes, I don't think this will be a problem.

As far as Database goes, perhaps it's good @prwteas opens a separate ticket for this.
We should have a discussion on which database we use.

I  think there is something to said for a noSql db like mongoDB.
They offer some flexibility. I am not sure about it yet thought.

@g7morris as far as server conf goes, in time, we should setup a user for the project and for @prwteas.
But first things first :-)

**Comment by g7morris** [comment]
@spllr dataviz server is ready. Sending you email with details. 

@prwteas @spllr will fill you in on details and access. 

Closing ticket as this is fulfilled.
