### ISSUE TITLE
DataViz repository structure

### ISSUE THREAD

**Issue by prwteas** [Appsterdam/DataViz#3]
I need some input and insight for how to structure the DataViz repository; I have created the basic RoR app (innodb) but where would you suggest to create the app folder: inside DataViz or create a separate repository? If inside, will I be committing from DataViz or DataViz/innodb? Merci!

**Comment by spllr** [comment]
I think DataViz/app (or innodb) should be fine.

We make it into it's own repository later on if needed.

**Comment by prwteas** [comment]
Will reopen in time
