### ISSUE TITLE
Code language

### ISSUE THREAD

**Issue by delware** [Appsterdam/DataViz#4]
Another decision to be made is the language to code everything in. When I look at the database suggestions, I see a few non main-stream database come around. So, I will make suggest the language I most enthusiastic about and work most efficient in: Smalltalk - seaside. It would cut short the database discussion too, because most convenient would be to use Gemstone as a database then....

More mainstream would be to use java.

**Comment by spllr** [comment]
Smalltalk... old skool purist style...

Although I would love to claim a SmallTalk project I am not sure if this would be the most ideal route to go.
Do you have developed a good lib of tool useful for this kind of project in SmallTalk?

We are currently using some ruby.

**Comment by prwteas** [comment]
Is this the official SmallTalk website: http://www.smalltalk.org ? There are a couple of broken links on the "learning" page, especially those referring to beginners...

**Comment by delware** [comment]
I did a data conversion using moose, but that is of course mainly for development. Making the data available on the web with seaside should be easy enough. I also know of some examples in SmallTalk reading the twitter api.

**Comment by delware** [comment]
And to start on SmallTalk you best start with http://www.seaside.st/download/pharo and http://seaside.gemstone.com/tutorial.html

**Comment by spllr** [comment]
If you are ok with it I suggest sticking with Ruby.
I have a whole bunch of scripts for handling the kind of data we need.

Also, we need a web gui and api so people can work with data. Ruby tends to be very good at this.

We can call some SmallTalk programs from the system if needed.

Database choice need to be made. @prwteas have you made up your mind yet? "To Sql or not to Sql"

**Comment by prwteas** [comment]
Given its comprehensive ecosystem, I am inclined to sticking with Ruby. Given the way that we are going to dig the data, I go for a noSQL, schema-less DB as MongoDB…

Diego, should it be a problem if we met to discuss further your thoughts on the modeling?

Petros

**Comment by delware** [comment]
Having a lot of scripts for the kind of data we need will help. And Ruby and MonoDB are a good combination. So definitely an option. I am not familiar with either of them, but let's discuss this further when we meet.

I thought Olga would set up a meeting for the beginning of next week. I have some time this afternoon, if you are all available.

**Comment by prwteas** [comment]
Yes we can keep the meeting that Olga has setup for beginning of next week. Do you imply that you also have some time today, this afternoon?

**Comment by delware** [comment]
Ok. We have decided to go with Ruby and MonoDB. So this issue can be closed.
