### ISSUE TITLE
Issues when saving multibyte chars in MongoDB.

### ISSUE THREAD

**Issue by prwteas** [Appsterdam/DataViz#5]
It seems that there is an issue with certain characters that are used in the meetup members' bios or wherever.
For example, this is the string:

``` ruby
a="Chris \xA5\xEB\xAE\xDFe\xA5"
```

I first convert it to BINARY and I then gsub it like this:

``` ruby
a.force_encoding("BINARY").gsub(0xA5.chr,"oo")
```

...which works fine:

``` ruby
=> "Chris oo\xEB\xAE\xDFeoo"
```

But it seems that I can not use the chr method if I use Regexp:

``` ruby
a.force_encoding("BINARY").gsub(/0x....?/.chr,"")
NoMethodError: undefined method `chr' for /0x....?/:Regexp
```

Any ideas?

**Comment by spllr** [comment]
Try adding this line to the top of the files handling the data:

# encoding: UTF-8

**Comment by prwteas** [comment]
I have tried that, no luck. However, it seems that this solution is applicable when the encoding is `ASCII-8BIT`. In our case, the encoding is already `UTF-8` and are the mutibyte characters that are causing the issue...

**Comment by spllr** [comment]
Can you point me to the commit? Push it to a branch and add link to the file or reference me in a comment on the file.

**Comment by prwteas** [comment]
https://github.com/Appsterdam/DataViz/tree/frompadrino

**Comment by spllr** [comment]
What do I do to reproduce the error?

**Comment by prwteas** [comment]
http://localhost:3000/import

and press import again

**Comment by delware** [comment]
Worked together with Petros on it: we filtered all special characters for now and replaced them by ?

Probably not good in the long run, but good enough for now.

**Comment by spllr** [comment]
Great! I will do pull the code tomorrow and see if can provide more permanent fix. 

So no blockers for now?

Send from mobile device
