### ISSUE TITLE
Population of an HTML table from dynamic fields

### ISSUE THREAD

**Issue by prwteas** [Appsterdam/DataViz#6]
It's me again!!!

I am trying to find which is the most _optimum_ way to populate an html table using the MongoDB dynamic fields.

For example, our Meetup data  are already modelled by the time they are being fetched, so defining a model doesn't sound so crazy an idea.

Otherwise, I could map the hashes and extract the keys for the table titles and all the values for the table data.

Is there any other way to do it?

**Comment by spllr** [comment]
Have a look at this. https://github.com/spllr/tabler

**Comment by delware** [comment]
We got something running now.
